### ISSUE TITLE
Generating data for the Users Tab

### ISSUE THREAD

**Issue by tsugawa** [KissLog-net/KissLog.Sdk#25]
Hi folks, is there any documentation to generate data for Users Tab?

I'm coding in ASP NET CORE 3.0 + Identity  + JWT. And my tab always display "There are no users captured for XXXXX".

I'm testing Kisslog in develop environment (https://localhost). Could this cause the problem?

Tks

**Comment by catalingavan** [comment]
Hi Ricardo,

KissLog reads the logged-in user info by accessing the `ClaimsIdentity` property:

```
private string GetUserIdentity(HttpRequest request)
{
    if (request.HttpContext.User.Identity.IsAuthenticated == true)
    {
        ClaimsPrincipal claimsPrincipal = (ClaimsPrincipal)request.HttpContext.User;	
        ClaimsIdentity identity = (ClaimsIdentity)claimsPrincipal.Identity;
        
        return identity.Name;
    }
    
    return null;
}
```

I made a small test:

**Login action**

```
[HttpPost]
public async Task<IActionResult> Login()
{
    string username = "catalingavan@gmail.com";

    ClaimsPrincipal principal = CreateIdentity(username);
    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

    return RedirectToAction("Index", "Home");
}

private ClaimsPrincipal CreateIdentity(string username)
{
    List<Claim> claims = new List<Claim>();

    claims.Add(new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name", username));
    
    ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
    return new ClaimsPrincipal(identity);
}
```

**Request log**

The username is captured correctly.

![image](https://user-images.githubusercontent.com/39127098/69901453-6179ac80-138a-11ea-91ec-9c5701e6f890.png)

To get more details about the possible reason, can you please share your login action?

**Comment by tsugawa** [comment]
Thank you @catalingavan. It worked.
