### ISSUE TITLE
Using Kisslog in Custom DLL

### ISSUE THREAD

**Issue by philvbprogrammer** [KissLog-net/KissLog.Sdk#26]
I want to be able to run KissLog in a Specific DLL that maybe used in several projects, but want the DLL to have its own identity for logging purposes.

**Comment by catalingavan** [comment]
Hi Phil,

I am not sure if I understand correctly your requirements:

Do you want to use an "internal" logger library, eg: `ISimpleLogger`, but still use KissLog in behind?

If this is the case, you can use an adapter.

In your code you will use `ISimpleLogger` - but, behind, it will actually use `KissLog`.

```csharp
// internal logger
public interface ISimpleLogger
{
    void Trace(string message);
    void Debug(string message);
    void Error(string message);
}
```

```csharp
// adapter
public class KissLogSimpleLoggerAdapter : ISimpleLogger
{
    private readonly KissLog.ILogger _logger;
    public KissLogSimpleLoggerAdapter(KissLog.ILogger logger)
    {
        _logger = logger;
    }

    public void Trace(string message)
    {
        _logger.Log(KissLog.LogLevel.Trace, message);
    }
    public void Debug(string message)
    {
        _logger.Log(KissLog.LogLevel.Debug, message);
    }
    public void Error(string message)
    {
        _logger.Log(KissLog.LogLevel.Error, message);
    }
}
```

```csharp

public class HomeController : Controller
{
    private readonly ISimpleLogger _simpleLogger;
    public HomeController(ILogger logger)
    {
        _simpleLogger = new KissLogSimpleLoggerAdapter(logger);
    }

    public IActionResult Index()
    {
        // using the ISimpleLogger
        _simpleLogger.Debug("Hello world!");

        return View();
    }
}
```

**Comment by philvbprogrammer** [comment]
Mmmm sort of. I want to just use kisslog in a dll. The dll Could be in console exe or http or core exe e.t.c
So the logging is in the dll and not in the application.

Example. The dll is a common functions dll
________________________________

**Comment by catalingavan** [comment]
Currently, KissLog functionality is packed in one dll: `KissLog.dll`.
This library has access to the `ILogger` interface, which is used to write log messages.

You can install this library (`KissLog.dll`) with NuGet manager, and simply reference the `ILogger` normally.

**MyApplication.Application.csproj**

```
PM> Install-Package KissLog
```

```csharp
using KissLog;

namespace MyApplication.Application
{
    public class GeneratePdfService
    {
        private readonly ILogger _logger;
        public GeneratePdfService(ILogger logger)
        {
            _logger = logger;
        }

        public async Task GeneratePdfAsync(string htmlPath)
        {
            if(!File.Exists(htmlPath))
            {
                _logger.Error($"Html path {htmlPath} was not found");
                return;
            }

            _logger.Info("Generating Pdf begin");

            // code 
        }
    }
}
```

If you want to avoid installing `KissLog.dll` in other projects, the solution would be to create a custom logger in your `MyApplication.Common.dll` library, eg: `ISimpleLogger`, and create an adapter for it (as in the previous comment).

If you use this path (and not using the `KissLog.dll` library directly), please note that you might lose some of the KissLog features.

**Comment by catalingavan** [comment]
Hi Phil,

I will close this issue as not replicable. KissLog SDK may already support the described functionality. Will reopen a new ticket if further details are necessary.

Thanks
