### ISSUE TITLE
is out KissLog.net?

### ISSUE THREAD

**Issue by tv1ffonseca** [KissLog-net/KissLog.Sdk#32]
Hello peoples!
Is out of service the url - https://kisslog.net/ ?

Regards,
Fernando.

**Comment by catalingavan** [comment]
Hi Fernando,

https://kisslog.net is up and running again, sorry for the inconvenience. It appears that just the user-interface has stopped. The logs should have been saved during the down-time.

Can you please confirm that it works ok now for you?

Thank you,
Catalin

**Comment by catalingavan** [comment]
I will close this issue. Thanks!
