### ISSUE TITLE
Dashboard does not list requests when the controller has the Authorize attribute.

### ISSUE THREAD

**Issue by danielts90** [KissLog-net/KissLog.Sdk#33]
I am implementing kisslog in an API that I am developing and I am having a problem that I cannot say if it is a bug or if it is a problem with my implementations.
The problem is that when a controller method uses the Authorize attribute, the physical log is generated but the request is not listed on the dashboard.

It's OK 
![image](https://user-images.githubusercontent.com/19877668/105351981-0deca280-5bcc-11eb-9afe-ab506a7d8f11.png)
![image](https://user-images.githubusercontent.com/19877668/105352210-615ef080-5bcc-11eb-90a9-fb943646cf08.png)

It's not OK
![image](https://user-images.githubusercontent.com/19877668/105352365-90756200-5bcc-11eb-8b22-0ed8f3b9d321.png)

**Comment by catalingavan** [comment]
Hi Daniel,

Can you please share the `Startup.Configure(IApplicationBuilder app)` code?

**Comment by danielts90** [comment]
Yes, 
I divided Startup into several classes,
if you need any more, let me know.

[LogStartup.txt](https://github.com/KissLog-net/KissLog.Sdk/files/5849371/LogStartup.txt)
[Startup.txt](https://github.com/KissLog-net/KissLog.Sdk/files/5849375/Startup.txt)

**Comment by catalingavan** [comment]
In AspNetCore the order of the Middleware is important, and I suspect this might be the issue.

I will need a copy of the physical log file which works ok, and the KissLog Internal Logs (you can save them to a `StringBuilder`:

```
static StringBuilder sb = new StringBuilder();

options.InternalLog = (message) =>
{
    sb.AppendLine(message);
};
```

![image](https://user-images.githubusercontent.com/39127098/105355366-55862500-5bf2-11eb-8bbc-196b8679d55c.png)


To simplify the code, can you temporary change the **Startup.cs** to the following, and see if this makes a difference?

I copied the LogStartup.cs into the Startup.cs, and I also added the `app.UseAuthorization();` and `app.UseAuthentication();`.

```
namespace Spx.Cor.Exportacao.Api
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuracao = configuration;
        }

        public IConfiguration Configuracao { get; }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        public void ConfigureServices(IServiceCollection servicos)
        {
            servicos.AddCorsCustomizado(Configuracao);

            servicos.AddDommelCustomizado();

            servicos.AddMemoryCache();

            servicos.AddHealthChecksCustomizado(Configuracao);

            servicos.AddAutoMapperCustomizado();

            servicos.AddAutenticacaoCustomizada(Configuracao);

            servicos.AddMvcCustomizado();

            servicos.AddSwaggerCustomizado(Configuracao);

            servicos.AddDICustomizado();

            servicos.AddLogCustomizado(Configuracao);
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseCorsCustomizado(env);

            app.UseExcecaoCustomizada();

            app.UseSwaggerCustomizado();

            app.UseHealthChecksCustomizado();

            app.UseMvcCustomizado();

            app.UseStaticFiles();
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseSession();

	    app.UseKissLogMiddleware(options => {
                ConfigureKissLog(options, Configuracao);
            });

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
		
	private static void ConfigureKissLog(IOptionsBuilder options, IConfiguration configuracao)
        {
            // optional KissLog configuration
            options.Options
                .AppendExceptionDetails((Exception ex) =>
                {
                    StringBuilder sb = new StringBuilder();

                    if (ex is System.NullReferenceException nullRefException)
                    {
                        sb.AppendLine("Important: check for null references");
                    }

                    return sb.ToString();
                });

            // KissLog internal logs
            options.InternalLog = (message) =>
            {
                Debug.WriteLine(message);
            };

            RegisterKissLogListeners(options, configuracao);
        }

        private static void RegisterKissLogListeners(IOptionsBuilder options, IConfiguration configuracao)
        {
            // multiple listeners can be registered using KissLogConfiguration.Listeners.Add() method

            // Register KissLog.net cloud listener
            options.Listeners.Add(new RequestLogsApiListener(new Application(
                configuracao["KissLog.OrganizationId"],
                configuracao["KissLog.ApplicationId"])
            )
            {
                ApiUrl = configuracao["KissLog.ApiUrl"]
            });

            // Register local text files listener
            options.Listeners.Add(new LocalTextFileListener(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "logs"))
            {
                FlushTrigger = FlushTrigger.OnMessage
            });
        }
    }
}
```

**Comment by catalingavan** [comment]
Thanks. Please trigger the request again WITH the Authorization attribute on (making it fail)

**Comment by danielts90** [comment]
Done
![image](https://user-images.githubusercontent.com/19877668/105360957-ef8ca400-5bd7-11eb-8f12-28d23c9d005c.png)

**Comment by catalingavan** [comment]
Can you please try few more time? This time it should work

**Comment by danielts90** [comment]
Now it's Ok 
![image](https://user-images.githubusercontent.com/19877668/105362663-e997c280-5bd9-11eb-8bc9-4584649d088b.png)
![image](https://user-images.githubusercontent.com/19877668/105362706-f7e5de80-5bd9-11eb-9fc6-b0114e38b37b.png)

**Comment by catalingavan** [comment]
Perfect. You helped me discover a misplaced validation rule on the server, thank you!
You can change the code back as it was previously, and it should work ok now.
Sorry for that.

**Comment by danielts90** [comment]
I'm so happy for contribute, 
Is the first time that i open a github issue.
