### ISSUE TITLE
Response Json and search for a SearchKey

### ISSUE THREAD

**Issue by bbarreto08** [KissLog-net/KissLog.Sdk#58]
![Capturar](https://user-images.githubusercontent.com/19316132/158714027-b6179570-9bd1-4c9c-82e9-042866504147.PNG)

I'm having problems trying to visualize the json response, I'm using Kisslog on-premises , the installation tutorial was followed: https://kisslog.net/Docs/on-premises.installation-guide.html

Everything is working, but I can't perform filters or view the response, I'm interested in buying a license, but how do I solve this problem so that I can finish my tests?

Problem demo: https://mega.nz/file/8xY2EByL#mOyUIcc4KVd_YHxF9911VNwl5coNbTtDWp9KwvqMdcM

I'm using windows server with all software in its latest version today.

**Comment by catalingavan** [comment]
Hi Bruno,

The default KissLog configuration has the Search and Files functionality disabled. However, they should work once we enable them.

Please go to `KissLog.Backend\Configuration\KissLog.json` file, and modify the following properties:

`"UploadRequestLogFiles.IsEnabled": true`
`"UploadRequestLogFiles.Provider": "MongoDbGridFS"`
`"RequestLogs.Search.Engine": "MongoDbTextSearch"`

The simplified example of `KissLog.Backend\Configuration\KissLog.json` should now look like this:

```json
{
  "UploadRequestLogFiles": {
    "IsEnabled": true,
    "Provider": "MongoDbGridFS",
    "MaximumFileSizeInBytes": 2097152,
    "Throttle": {
      "IsEnabled": true,
      "RequestLimit": 1,
      "IntervalInSeconds": 20
    }
  },
  "RequestLogs": {
    "Search": {
      "Engine": "MongoDbTextSearch",
      "IndexInputStream": true,
      "KeyRange": [ 1, 100 ],
      "ValueRange": [ 1, 100 ]
    }
  }
}
```

Restart both KissLog.Backend and KissLog.Frontend IIS applications so they can reload the new configuration changes.

Let me know if these changes fixes the issue.

Thank you

**Comment by bbarreto08** [comment]
Yes, this configuration solved the problem. Thank you very much.

I would be very grateful if you could send me the documentation of all possible configurations.

**Comment by catalingavan** [comment]
Hi Bruno,

Happy that it worked out.

All the configuration options for KissLog on-premises are available here:

https://kisslog.net/Docs/on-premises.kisslog-backend.html
https://kisslog.net/Docs/on-premises.kisslog-frontend.html

For example, the Search configuration is here:
https://kisslog.net/Docs/on-premises.kisslog-backend.html#search

And the Files configuration is here:
https://kisslog.net/Docs/on-premises.kisslog-backend.html#uploadrequestlogfiles

Thanks
