### ISSUE TITLE
kisslog sdk error UnauthorizedAccessException

### ISSUE THREAD

**Issue by rocketRobin** [KissLog-net/KissLog.Sdk#67]
Windows server 2022 and iis 10

![image](https://user-images.githubusercontent.com/9987850/225616915-b7e1af37-2639-4939-afb1-9f357776e280.png)

KissLog.Exceptions.LogStringAsFileException: KissLog: Error when trying to log as file the string with length 498
 ---> System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Path.GetTempFileName()
   at KissLog.TemporaryFile.GetTempFileName(String extension)
   at KissLog.TemporaryFile..ctor(String extension)
   at KissLog.TemporaryFile..ctor()
   at KissLog.LoggerData.FilesContainer.LogAsFile(String contents, String fileName)
   --- End of inner exception stack trace ---

Every log will contains this error

**Comment by catalingavan** [comment]
hi Robin,
one possible reason for the exception can be the one mentioned below. Can you check the temp folder and see how many files there are?
https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettempfilename?view=net-7.0#remarks

**Comment by rocketRobin** [comment]
I clear the temp folder ，restart app，and the problem still there

![image](https://user-images.githubusercontent.com/9987850/225780675-aa49bf8e-4858-4e84-b142-a72f3eaf0cfe.png)
![image](https://user-images.githubusercontent.com/9987850/225780790-c273fb9d-3b6e-416e-8fce-75fa1b4de3d2.png)

**Comment by rocketRobin** [comment]
I fix this, step is:

1 iis
2 app pool
3 choose the app
4 advanced setting
5 identity change to LocalSystem

done

**Comment by catalingavan** [comment]
hi Robin,
thanks a lot for the feedback. That is correct.
To save memory, KissLog is using temporary files to manage blobs and other large contents. The temp files are created with `Path.GetTempFileName()`, which apparently needs special permissions to run.
I will consider creating a fallback and save the temp files under the application execution path.

https://github.com/KissLog-net/KissLog.Sdk/blob/3ce7a0761ed05faa1d4a88bcbd7d228511c4e800/src/KissLog/TemporaryFile.cs#L61
